# -*- coding: utf-8 -*-
"""day2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WG4zqO5RP-9ptBgyDRGj33oxs0a_fmBp
"""

# day2 basics of python input from the user and + operator in string and many more concept


name='arslan'
father_name='rizwan'
full_name=name + " " + father_name
print(full_name)


age=23
print(age)
print(type(age))
print(str(age))
print(type(age))

gf_name=input("enter her name:")
print(full_name,"gf name is : ",gf_name)
her_age=input("her age:")
print("her age is:",her_age)
print(type(her_age))


name="arslan"
last_name='rizwan'
city='lahore'
print(f"my name is {name} {last_name} i live in {city}")
full_name=name + ' '+ last_name
print(full_name)


name= input("name:")
city=input('city:')
uni=input('university:')
print(f"hello {name}\n you live in {city}\n you study at {uni}")

age = int (input("enter age "))
print(f"the age is : {age}")


num1=int(input("enter num1:"))
num2=int(input("enter num2:"))

print("the sum:=",num1+num2)
print("the diff:=",num1-num2)
print("the product:=",num1*num2)
print("the div:=",num1/num2)

TOTAL_CREDITS=130
credit=int(input("Enter completed credits:"))
print(f"the completed credits are = {credit}")
remaing_credit=TOTAL_CREDITS-credit
print(f"total credit: {remaing_credit}")


curr_age=int(input("curr age ="))
print(f"curr age is this :{curr_age}")
curr_age+=5
print(f"aproc age in next 5 year this :{curr_age}")

