# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0UiJzc_G8sOhCv8xjjqOrcIEPC0HTbV
"""

# day 3 conditioanl statment with logical operators



choice=int(input("user to enter a number:"))
if choice>0:
  print("positive")
elif choice==0:
  print("exctly zero")
else:
    print("negetive")

num= int(input("enter the num to check="))
if num%2==0:
  print(f"{num} is even ")
else:
  print(f"{num} is odd ")

gpa=float(input('enter your gpa:'))
com_cr=int(input('enter total credits:'))
gpa_ok= gpa>=2.5
cr_ok= com_cr>=60
if gpa_ok and cr_ok :
  print("eligible")
else:
  print("not eligible")
if not gpa_ok and not cr_ok:
  print("not eligible")
elif not gpa_ok:
  print("gpa req not meet")
else :
  print("credits not ok")

amount= float(input("enter total purchase:$"))
ask=input("ask they are studunt or not:")

if amount>=100000 :
    discount = 0.20
    final = amount - (amount * discount)
    if ask == "yes":
        final = final - (amount * 0.05)
elif amount>=50000:
     discount=0.10
     final=amount - (amount * discount)
     if ask == "yes":
        final = final - (amount * 0.05)
else:
  print("no discount")

print(f"original price:{amount}")
discount=amount-final
print(f"discount:{discount}")
print(f"final price:{final}")

gpa=float(input('enter your gpa:'))
erned_cr=int(input('enter total credits:'))
family_income=int(input('enter family income:'))
if (gpa>=3.5 and erned_cr>=60) or (gpa>=3.0 and erned_cr>=60 and family_income>=100000):
  print("eligible")
else:
  print("not eligible")


username=input("enter user name:")
password=input('enter the password')
if (username=='arslan'and password=='jannat1726'):
  print("login successful")
elif (username=='arslan' and password!='jannat1726'):
    print('invalid  password')
elif (username!='arslan' and password=='jannat1726'):
    print('invalid username')
else:
    print('invalid username and password')

