# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THWhD8CLm5hSOWX2P4ituIhqYm0Yf2-R
"""

lst=['aws','docker','python','Ai','web']
print(lst[0])
print(lst[-1])
lst[2]='fastapi'
lst.append('Machine learning')
print(lst)
print(len(lst))
lst.remove('Ai')
print("the updated list is",lst)

skills = ["Python", "SQL", "FastAPI", "PyTorch"]
temp =skills[0]
skills[0]=skills[-1]
skills[-1]=temp
print(skills)


student={
    'name':'arslan',
    'age': 23,
    'gpa': 2.22,
    'university':"fast"
}
print(student['name'])
print(student['gpa'])

student['credits'] =73
print(student)
student['gpa']=2.3
print(student)

skills = [
    "Python",
    "SQL",
    "Python",
    "AI",
    "SQL",
    "FastAPI",
    "Python",
    "AI"
]
unique_skills=set(skills)
print(unique_skills)
print(len(skills))
print(len(unique_skills))


student = {
    "name": "arslan",
    "age": 23,
    "gpa": 2.22,
    "credits": 70,
    "skills": ["python", "sql", "git"]
}

student['skills'].append('fastapi')
student['gpa']=2.5
student['status']='active '
del student['age']
print(student['name'])
print(student['skills'])
print(student)



course={
    'tbw':3,
    'la':3,
    'scd':3,
    'cn': 3,
    'sqe':3,
    'cn_lab':2,
    "holy":2,
    'bilo':76
}
course['scd_lab']=1
del course['holy']
course['cn_lab']=1


students={
    "stu1":{
"name" :"arslan",
  'gpa':2.22,
    'credit':70,
    }
    ,
    "stu2":{
"name" :"bilal",
  'gpa':2.95,
    'credit':75,
    }
    ,
    'stu3':{
        "name" :"peer",
  'gpa':3.33,
    'credit':73,

    }

}

print(students['stu2']['name'])
print(students['stu3']['gpa'])
students['stu1'].update({'gpa':2.33})
students['stu2']['status'] = 'active'
print(students)


student={
    'name': "arslan",
    'gap': 2.22,
    'credit':70,
    'skills':["Python", "SQL", "Git",'Python','SQL','SQL'],
    'completed':["Programming Fundamentals",
        "OOP",
        "Data Structures"]
    }
student['skills'].append("fastapi")
student['skills'].remove("Git")
student['completed'].append('probility')
print(len (student['skills']))
print(len (student['completed']))
unique_skills=set(student['skills'])
print(unique_skills)
print(student)

